### ISSUE TITLE
AsyncConnection - IOException: Cleartext HTTP traffic to X not permitted

### ISSUE THREAD

**Issue by depbmhe** [eit74/BeaconApp#11]
```
W/System.err: java.io.IOException: Cleartext HTTP traffic to cert.stokoloko.dev not permitted

        at com.android.okhttp.HttpHandler$CleartextURLFilter.checkURLPermitted(HttpHandler.java:115)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:458)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:407)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:244)
        at java.net.URL.openStream(URL.java:1072)
        at de.rvwbk.eit74.beaconapp.restconnection.connection.RestConnection.buildCerfiticate(RestConnection.java:304)
        at de.rvwbk.eit74.beaconapp.restconnection.connection.RestConnection.request(RestConnection.java:52)
        at de.rvwbk.eit74.beaconapp.restconnection.connection.RestConnection.get(RestConnection.java:210)
W/System.err:     at de.rvwbk.eit74.beaconapp.restconnection.connection.AsyncConnection.doInBackground(AsyncConnection.java:48)
        at android.os.AsyncTask$2.call(AsyncTask.java:333)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)```

**Comment by depbmhe** [comment]
Call:
```AsyncConnection ac = new AsyncConnection();
        TaskObject task = new TaskObject();
        ac.get(task, questID);

        for (Map.Entry<String, String> entry : task.getMap().entrySet()) {
            System.out.println(entry.getKey()+" "+entry.getValue());
        }```
